# Generated by Django 4.2.4 on 2023-09-05 07:27

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_app", "0002_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                (
                    "user_DOB",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date of birth"
                    ),
                ),
                (
                    "user_phone_no",
                    models.CharField(
                        help_text="Enter your phone number 03xxxxxxxxx",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "03\\d{9}$",
                                "Phone number format needs to be 03xxxxxxxxx",
                            )
                        ],
                    ),
                ),
                (
                    "user_cnic",
                    models.CharField(
                        help_text="Enter cnic in format xxxxx-xxxxxxx-x",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\d{5}\\-\\d{7}\\-\\d{1}",
                                "CNIC format needs to be xxxxx-xxxxxxx-x",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
