# Generated by Django 4.2.4 on 2023-09-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_designation",
            field=models.CharField(
                default=None,
                help_text="Enter your designtion",
                max_length=40,
                null=True,
            ),
        ),
    ]
