# Generated by Django 4.2.4 on 2023-09-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_profile_user_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_address",
            field=models.CharField(help_text="Enter Address", max_length=70, null=True),
        ),
    ]
