# Generated by Django 4.2.4 on 2023-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_image",
            field=models.ImageField(default="uplaods/empty.png", upload_to="uploads/"),
        ),
    ]
