# Generated by Django 4.2.4 on 2023-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_alter_profile_user_designation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_image",
            field=models.ImageField(default="images/empty.png", upload_to="images/"),
        ),
    ]
